main: migrate strncasecmp to g_ascii_strncasecmp
This fixes
gerbv-2.13.0/src/main.c: In function ‘getopt_lengh_unit’:
gerbv-2.13.0/src/main.c:1279:13: error: implicit declaration of function ‘strncasecmp’; did you mean ‘g_strncasecmp’? [-Wimplicit-function-declaration]
 1279 |         if (strncasecmp(optarg, "mm", 2) == 0) {
      |             ^~~~~~~~~~~
      |             g_strncasecmp

The other option would be to include <strings.h> which is covered by config.h,
however since g_ascii_strcasecmp is already used, this fix looks more
reasonable.