fix build error: "undefined reference to `selection_add_item'", etc.
functions, being declared inside .c source as inline, are thrown away by compiler,
thus producing multiple linkage problems:
render.c:517: undefined reference to `selection_clear'
./.libs/libgerbv.so: undefined reference to `selection_add_item'
and so on